# Generated by Django 3.0.8 on 2020-07-24 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories_listingpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listingtype', to='auctions.Categories'),
        ),
    ]
