# Generated by Django 3.0.8 on 2020-08-03 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200724_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpage',
            name='user',
            field=models.ForeignKey(default='ducnguyen89', on_delete=django.db.models.deletion.CASCADE, related_name='listinguser', to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
    ]
