# Generated by Django 3.0.8 on 2020-08-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_delete_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('V', 'vehicles'), ('P', 'pets'), ('A', 'antiques'), ('M', 'media'), ('S', 'sports'), ('H', 'household'), ('C', 'clothing')], default='M', max_length=1),
        ),
    ]
