# Generated by Django 3.0.8 on 2020-08-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listingpage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingpage',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
