# Generated by Django 3.0.8 on 2020-08-05 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_biddings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biddings',
            name='bidder',
        ),
        migrations.AddField(
            model_name='biddings',
            name='bidder',
            field=models.ManyToManyField(related_name='bidders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='biddings',
            name='item_id',
        ),
        migrations.AddField(
            model_name='biddings',
            name='item_id',
            field=models.ManyToManyField(related_name='biddingitems', to='auctions.ListingPage'),
        ),
    ]
