# Generated by Django 3.0.8 on 2020-08-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200805_0446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biddings',
        ),
    ]
